### ISSUE TITLE
Potential Use Cases?

### ISSUE THREAD

**Issue by Syzygianinfern0** [amitness/open-in-overleaf#1]
Hi there! I came across your Reddit extension and I must say it caught my attention. I'm curious to know more about it and how it can be utilized. If you don't mind, could you please share some potential use cases? It would be great if you could add this information to your project's readme as well, as it would be highly beneficial. Thanks!

**Comment by amitness** [comment]
@Syzygianinfern0 That's a great idea. I will update the README

Regarding usecases, there has been a good discussion on reddit [here](https://www.reddit.com/r/MachineLearning/comments/12kl20l/comment/jg3ienx/?utm_source=share&utm_medium=web2x&context=3)
