### ISSUE TITLE
Question about source

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#10]
I am wondering if it is possible to improve the extension by sending the source to overleaf , then adding a small latex code block at the beginning of the main file, or right before \begin{document}. 

My use case is I have terrible eyesight and need to compile to large font , so I put the following code block right before \begin{document} always after I open in Overleaf.

Code:

\renewcommand{\mddefault}{bx}
\renewcommand\seriesdefault{b}
\renewcommand\bfdefault{bx} % just to make sure
\usepackage{times}
\usepackage[fontsize=13pt]{scrextend}
\makeatletter
\@ifpackageloaded{geometry}{\AtBeginDocument{\newgeometry{letterpaper,left=1.56in,right=1.56in,top=1.71in,bottom=1.77in}}}{\usepackage[letterpaper,left=1.56in,right=1.56in,top=1.71in,bottom=1.77in]{geometry}}
\AtBeginDocument{\newgeometry{letterpaper,left=1.56in,right=1.56in,top=1.71in,bottom=1.77in}}
\makeatother

**Comment by amitness** [comment]
Sadly, this is beyond the scope. This extension simply converts the tar file taken from arxiv and converts it into a zip file that overleaf can read. The parsing logic is completely on overleaf's end and we have no oversight on how they do it.

A solution could be to write some logic to extract the zip, figure out the main .tex file (tricky?) and then add this codeblock in the beginning. But the latex source code for the different papers varies and it would be non-trivial to figure out which is the main .tex file. Maybe someone with experience with latex parsing could handle this.
