### ISSUE TITLE
blurry frozen screen

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#11]
https://arxiv.org/abs/2112.02952 this link causes the freezing screen. It seem to not be an issue with HF crashed, other arxiv docs work.

**Comment by amitness** [comment]
The source code uploaded by the authors of this particular paper seem to not be a valid `.tar.gz` file. This is causing the conversion script on the huggingface server to fail. 

TODO: Add some exception handling to restore the blur when conversion/server fails and notify user with an alert.

**Comment by amitness** [comment]
The exception handling has been added.
