### ISSUE TITLE
arxiv page updated, extension broken

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#12]
![image](https://github.com/amitness/open-in-overleaf/assets/6448285/bbcba871-3fa7-4b7d-915b-a15e1e08935f)
arxiv page updated and send to overleaf no longer appears

**Comment by andyz245** [comment]
also getting this issue, would appreciate a fix!

**Comment by amitness** [comment]
Thanks for flagging! I have pushed an update to fix this, waiting for chrome to review. The extension should automatically update on your end in a few hours.

**Comment by jasondlee88** [comment]
Thanks!
