### ISSUE TITLE
Blurry screen

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#14]
![image](https://github.com/amitness/open-in-overleaf/assets/6448285/6ee0feda-0828-4740-918a-ca6074c0219a)
Blurry screen, probably the HF is down?

**Comment by amitness** [comment]
@jasondlee88 Yeah, it was. 

I have also improved the UX now, so the blurry screen problem shouldn't occur even if HF is down.

It would instead show you directly that the conversion failed.
<img width="332" alt="image" src="https://github.com/amitness/open-in-overleaf/assets/8587189/bcd2468e-b10c-474c-a37e-e33083932454">

Have pushed the updated extension, it will show up in your chrome in few hours.
