### ISSUE TITLE
Huggingface space running but still error?

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#15]
![image](https://github.com/amitness/open-in-overleaf/assets/6448285/229b23ea-b8a7-4447-870a-0d9dcaa12759)
The HF space is up but I am still getting this error.

**Comment by amitness** [comment]
@jasondlee88 Upgrading gradio breaks API access via HTTP now. I've downgraded gradio. 


Let's see how long it works. Otherwise, have to find some other free hosting alternative
