### ISSUE TITLE
extension stopped working this tuesday

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#3]
Hi all,
The extension stopped working on tuesday. It freezes at the screen below on arxiv. 

![image](https://github.com/amitness/open-in-overleaf/assets/6448285/85a8bd32-df5a-4c89-b4a4-dbb2686e07f6)

**Comment by amitness** [comment]
@jasondlee88 Fixed! Thanks for pointing out

<img width="1295" alt="image" src="https://github.com/amitness/open-in-overleaf/assets/8587189/3ff8b685-6add-46a0-b8b1-34e4c92588f8">

**Comment by jasondlee88** [comment]
Wow thanks so much
