### ISSUE TITLE
references become (???)

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#4]
On some arxiv ports, the references become (???) 
Is this because the .bbl file is being overwritten by overleaf?

![image](https://github.com/amitness/open-in-overleaf/assets/6448285/23900f7e-f86d-4861-b614-80193759c470)

**Comment by amitness** [comment]
@jasondlee88 Yes, it's something on the overleaf end. The extension doesn't do any pre-processing and simply forwards the raw latex code over to overleaf
