### ISSUE TITLE
Conflict with arxiv-utils

### ISSUE THREAD

**Issue by yzy1996** [amitness/open-in-overleaf#5]
When I use two plugins at the same time, the download function is normal, but there is no response when I open Overleaf.

ref: [arxiv-utils](https://github.com/j3soon/arxiv-utils)

**Comment by amitness** [comment]
@yzy1996 I tried it with latest version, it's working for me even when arxiv-utils is installed.

**Comment by yzy1996** [comment]
Thank you, the latest version is working well.
