### ISSUE TITLE
open in overleaf stopped working this weekend

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#6]
![image](https://github.com/amitness/open-in-overleaf/assets/6448285/7816a83f-d741-4000-b60e-5d57e1d8dca4)
Hi all,
The extension stopped working over the weekend. Any suggestions on how to fix?

**Comment by amitness** [comment]
@jasondlee88 Please try now! It should be fixed.

<img width="1280" alt="image" src="https://github.com/amitness/open-in-overleaf/assets/8587189/c57797ce-af9b-4620-b00e-cf61b4d29853">
