### ISSUE TITLE
It somehow does not work for Edge

### ISSUE THREAD

**Issue by tianyu-z** [amitness/open-in-overleaf#8]
It shows 
![image](https://github.com/amitness/open-in-overleaf/assets/53099276/88e2c890-29d6-477b-8ef3-07afadd91b3a)
but when I click on "Open in Overleaf", nothing happened. If I use Chrome, it works fine. It was functional well on Edge.

**Comment by tianyu-z** [comment]
Edge Version: 118.0.2088.61 (Official build) (64-bit).

OS Information
Edition	Windows 11 Pro
Version	22H2
OS build	22621.2428

**Comment by amitness** [comment]
@tianyu-z Could you try the latest version?

**Comment by tianyu-z** [comment]
It works! Thanks a lot.
