### ISSUE TITLE
same issue as before (getting the fuzzy screen)

### ISSUE THREAD

**Issue by jasondlee88** [amitness/open-in-overleaf#9]
![image](https://github.com/amitness/open-in-overleaf/assets/6448285/9ca25e48-8ee7-41c2-b0a1-018fbb88bee3)
see image

**Comment by amitness** [comment]
@jasondlee88 Seems to be a problem on huggingface end. The [space](https://huggingface.co/spaces/amitness/open-in-overleaf) that I use to convert the tar file to a zip file stopped abruptly. I restarted it, so it should work for now.

I will look into why it keeps getting stuck once in a while.
